### ISSUE TITLE
Orcon HRU parse unknown `2210`

### ISSUE THREAD

**Issue by remyderuysscher** [ramses-rf/ramses_cc#65]
The Orcon ~RF15 control unit [https://orcon.nl/product/afstandsbediening-15rf/](url)~ address 18:071957 HRU Fan sends 2210 messages, do you know what they are?

```python
Logger: ramses_rf.protocol.message
Source: /usr/local/lib/python3.11/site-packages/ramses_rf/protocol/message.py:350
First occurred: 25 juni 2023 om 19:56:07 (5 occurrences)
Last logged: 25 juni 2023 om 20:13:20

RP --- 32:155021 18:071957 --:------ 2210 042 00FF00FFFFFF0000000000FFFFFFFFFF00FFFFFF0000000000FFFFFFFFFFFFFFFF000000000000020800 < AssertionError(Support the development of ramses_rf by reporting this packet)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ramses_rf/protocol/message.py", line 331, in _validate
    result = PAYLOAD_PARSERS.get(self.code, parser_unknown)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ramses_rf/protocol/parsers.py", line 140, in wrapper
    result = fnc(payload, msg, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ramses_rf/protocol/parsers.py", line 1335, in parser_2210
    assert payload in (
           ^^^^^^^^^^^^
AssertionError: Support the development of ramses_rf by reporting this packet
```

**Comment by Kars-de-Jong** [comment]
@silverailscolo Perhaps rename the issue to "Orcon fan parse unknown `2210`"?

**Comment by remyderuysscher** [comment]
> Pretty sure that 18:071957 is not the remote but the HGI (i.e. HomeAssistant). Fans don't send `RP` messages to remotes, the fan (32:155021) sends that reply in response to a `RQ` from HomeAssistant. I have that remote too, it sends `22F1` messages which are parsed correctly.
> 
> The values in `2210` do change now and then on my system, they are related to automatic speed change based on humidity or CO2. When my fan is in `auto` mode, the content of `2210` changes when the speed is increased to `speed 2` due to humidity being detected, and also when the fan is running faster based on CO2 level.
> 
> Fan speed at 20.5% due to increased CO2 levels, `hvac_state` included for comparison :
> 
> ```
> 20:45:10.349 ||  32:xxxxxx |            |  I | hvac_state       |  00  || {'hvac_id': '00', 'exhaust_fan_speed': 0.205, 'fan_info': 'auto'
> , '_unknown_fan_info_flags': [0, 0, 0], 'air_quality': None, 'co2_level': None, 'indoor_humidity': 0.58, 'outdoor_humidity': 0.58, 'exhaus
> t_temp': 24.0, 'supply_temp': 23.7, 'indoor_temp': 23.23, 'outdoor_temp': 23.24, 'speed_capabilities': ['off', 'low_med_high', 'timer', 'b
> oost', 'auto'], 'bypass_position': 1.0, 'supply_fan_speed': 0.205, 'remaining_mins': 0, 'post_heat': None, 'pre_heat': None, 'supply_flow'
> : 22.5, 'exhaust_flow': 22.5}
> 20:46:03.380 ||  18:xxxxxx |  32:xxxxxx | RQ | unknown_2210     |      || {}
> 20:46:03.444 ||  32:xxxxxx |  18:xxxxxx | RP | unknown_2210     |      || {'unknown_10': '29', 'unknown_20': '02', 'unknown_78': '00', 'unknown_80': '08', 'unknown_82': '00'}
> ```
> 
> This corresponds to the content of `unknown_10` (29 hex is 41 decimal, divided by 2 gives 20.5).
> 
> `unknown_10` is `FF` on my system when the fan is running at default speed in `auto` mode, or when the speed is controlled manually.
> 
> Same when running at 44% because of the humidity sensor:
> 
> ```
> 06:05:21.360 ||  32:xxxxxx |            |  I | hvac_state       |  00  || {'hvac_id': '00', 'exhaust_fan_speed': 0.44, 'fan_info': 'auto',
>  '_unknown_fan_info_flags': [0, 0, 0], 'air_quality': None, 'co2_level': None, 'indoor_humidity': 0.64, 'outdoor_humidity': 0.6, 'exhaust_temp': 18.3, 'supply_temp': 22.5, 'indoor_temp': 22.63, 'outdoor_temp': 17.04, 'speed_capabilities': ['off', 'low_med_high', 'timer', 'boost', 'auto'], 'bypass_position': 0.0, 'supply_fan_speed': 0.44, 'remaining_mins': 0, 'post_heat': None, 'pre_heat': None, 'supply_flow': 48.88, 'exhaust_flow': 48.61}
> 06:06:40.034 ||  18:xxxxxx |  32:xxxxxx | RQ | unknown_2210     |      || {}
> 06:06:40.095 ||  32:xxxxxx |  18:xxxxxx | RP | unknown_2210     |      || {'unknown_10': '58', 'unknown_20': '03', 'unknown_78': '00', 'unknown_80': '08', 'unknown_82': '00'}
> ```
> 
> This corresponds to the content of `unknown_10` (58 hex is 88 decimal, divided by 2 gives 44).
> 
> Based on this we can also assign meaning to `unknown_20`, it is `02` when fan speed is increased by CO2-level, and `03` when fan speed is increased by humidity, and it is `00` when idle.
> 
> EDIT: Oh, and these values are repeated in the packet, so I guess it's values for the supply fan and for the exhaust fan.

Correct  18:071957  is the Home Assistant HGI.

**Comment by silverailscolo** [comment]
@remyderuysscher @Kars-de-Jong Could one of you provide a complete (incl. time stamp) packet log for a '03' request?
What Kars pasted in his comment is the parsed payload.

**Comment by silverailscolo** [comment]
Thanks. With the PR linked above, for example your last packet will be parsed as:
`{'exhaust_fan_speed': 0.335, 'req_reason': 'CO2', 'unknown_78': '00', 'unknown_80': '08', 'unknown_82': '00'}`
A user can pick that up in ramses_cc with a template sensor when I expose the 2 fields.
